<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <!-- Specific properties -->
    <PropertyGroup>
        <Product>Monero LWS CSharp library</Product>
        <PackageId>MoneroLwsNet</PackageId>
        <Description>The C# Monero Light Wallet Server library</Description>
        <!-- version is taken from git tag when releasing -->
        <Version Condition=" '$(Version)' == '' ">1.0.0</Version>
        <Authors>The Btcpay-Monero Team</Authors>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
        <PackageProjectUrl>https://btcpay-monero.github.io/monero-lws-csharp/</PackageProjectUrl>
        <RepositoryUrl>https://github.com/btcpay-monero/monero-lws-csharp</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>monero, lws</PackageTags>
        <Company>btcpay-monero</Company>
        <PackageIcon>logo.png</PackageIcon>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <!-- Package logo -->
    <ItemGroup>
        <None Include="..\logo.png" Pack="true" PackagePath="\" />
    </ItemGroup>

    <!-- Deterministic build -->
    <ItemGroup>
        <PackageReference Include="DotNet.ReproducibleBuilds" Version="2.0.5" PrivateAssets="All" />
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" />
    </ItemGroup>

</Project>