name: Code format check

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Code format check
        run: |
          dotnet tool install -g dotnet-format
          dotnet format monero-lws-csharp.sln --no-restore --verify-no-changes --verbosity diagnostic